language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
env:
  - DJANGO='Django>=1.2,<1.3'
  - DJANGO='Django>=1.3,<1.4'
  - DJANGO='Django>=1.4,<1.5'
  - DJANGO='Django>=1.5,<1.6'
  - DJANGO='Django>=1.6,<1.7'
  - DJANGO='Django>=1.7,<1.8'
  - DJANGO='Django>=1.8,<1.9'
matrix:
  exclude:
    # Django >= 1.7 does not support Python 2.6
    - python: "2.6"
      env: DJANGO='Django>=1.7,<1.8'
      env: DJANGO='Django>=1.8,<1.9'
install:
  - pip install --use-mirrors $DJANGO
script:
  - make test
